version: '1'

services:
  frontend:
    container_name: pokemon-evolution-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: "pokemon-evolution-dev:1.0.0"
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true``